service: sf-assignment-pow
frameworkVersion: '3'
configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  lambdaHashingVersion: 20201221
  memorySize: 256
  logRetentionInDays: 14
  timeout: 300

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    packager: yarn
    minify: false
    sourcemap: false
    target: node16
    watch:
      pattern: ['src/**/*.ts']

# functions:
#   graphql:
#     handler: src/fn_graphql.handler
#     events:
#       - httpApi: '*'

functions:
  explorer:
    handler: handlers.explorerHandler
    events:
      - httpApi:
          path: /graphql
          method: get
  graphql:
    handler: handlers.graphQLHandler
    events:
      - httpApi:
          path: /graphql
          method: post
  calculateSingleDayEnergyConsumption:
    handler: handlers.getBlockDataForDay
    events:
      - httpApi:
          path: /calculateSingleDayEnergyConsumption
          method: post
